export const sampleOnBallDefenseStats =
[
  {
     "code": "totals",
     "title": "Team Name",
     "pts": 1554,
     "plays": 1780,
     "scorePct": 39.1,
     "tovPct": 16.5,
     "fgMiss": 769,
     "totalPts": -1,
     "totalScorePct": -1,
     "totalPlays": -1,
     "uncatPts": -1,
     "uncatPlays": -1,
     "uncatScorePct": -1,
     "uncatPtsPerScPlay": -1
  },  [
   {
      "code": "Code1",
      "title": "#1 Player1",
      "pts": 170,
      "plays": 216,
      "scorePct": 32.4,
      "tovPct": 15.7,
      "fgMiss": 111,
      "totalPts": -1,
      "totalScorePct": -1,
      "totalPlays": -1,
      "uncatPts": -1,
      "uncatPlays": -1,
      "uncatScorePct": -1,
      "uncatPtsPerScPlay": -1
   },
   {
      "code": "Code2",
      "title": "#02 Player2",
      "pts": 159,
      "plays": 170,
      "scorePct": 41.2,
      "tovPct": 11.8,
      "fgMiss": 79,
      "totalPts": -1,
      "totalScorePct": -1,
      "totalPlays": -1,
      "uncatPts": -1,
      "uncatPlays": -1,
      "uncatScorePct": -1,
      "uncatPtsPerScPlay": -1
   },
   {
      "code": "Code3",
      "title": "#13 Player3",
      "pts": 151,
      "plays": 169,
      "scorePct": 37.3,
      "tovPct": 16,
      "fgMiss": 78,
      "totalPts": -1,
      "totalScorePct": -1,
      "totalPlays": -1,
      "uncatPts": -1,
      "uncatPlays": -1,
      "uncatScorePct": -1,
      "uncatPtsPerScPlay": -1
   },
   {
      "code": "Code4",
      "title": "#99 Player4",
      "pts": 109,
      "plays": 107,
      "scorePct": 39.3,
      "tovPct": 12.1,
      "fgMiss": 52,
      "totalPts": -1,
      "totalScorePct": -1,
      "totalPlays": -1,
      "uncatPts": -1,
      "uncatPlays": -1,
      "uncatScorePct": -1,
      "uncatPtsPerScPlay": -1
   },
   {
      "code": "Code5",
      "title": "#21 Player5",
      "pts": 103,
      "plays": 148,
      "scorePct": 31.8,
      "tovPct": 14.9,
      "fgMiss": 79,
      "totalPts": -1,
      "totalScorePct": -1,
      "totalPlays": -1,
      "uncatPts": -1,
      "uncatPlays": -1,
      "uncatScorePct": -1,
      "uncatPtsPerScPlay": -1
   },
   {
      "code": "Code6",
      "title": "#66 Player6",
      "pts": 52,
      "plays": 88,
      "scorePct": 26.1,
      "tovPct": 11.4,
      "fgMiss": 54,
      "totalPts": -1,
      "totalScorePct": -1,
      "totalPlays": -1,
      "uncatPts": -1,
      "uncatPlays": -1,
      "uncatScorePct": -1,
      "uncatPtsPerScPlay": -1
   },
   {
      "code": "Code7",
      "title": "Player 7",
      "pts": 76,
      "plays": 95,
      "scorePct": 32.6,
      "tovPct": 14.7,
      "fgMiss": 50,
      "totalPts": -1,
      "totalScorePct": -1,
      "totalPlays": -1,
      "uncatPts": -1,
      "uncatPlays": -1,
      "uncatScorePct": -1,
      "uncatPtsPerScPlay": -1
   } ]
];
