export const sampleOnBallDefenseStats = // Look for "Use to generate unit test artefact" in OnBallDefenseModal
[
   {
      "code": "totals",
      "title": "Team",
      "pts": 1158,
      "plays": 1336,
      "scorePct": 39.2,
      "tovPct": 13.4,
      "fgMiss": 615,
      "fgMade": 424,
      "sfPct": 6.5,
      "totalPts": -1,
      "totalScorePct": -1,
      "totalPlays": -1,
      "uncatPts": -1,
      "uncatPlays": -1,
      "uncatScorePct": -1,
      "uncatPtsPerScPlay": -1,
      "totalSfPlays": -1,
      "totalTos": -1,
      "totalFgMade": -1,
      "totalFgMiss": -1,
      "uncatSfPlays": -1,
      "uncatTos": -1,
      "uncatFgMade": -1,
      "uncatFgMiss": -1
   }, [
   {
      "code": "PlayerOne",
      "title": "#1 Player One",
      "pts": 81,
      "plays": 106,
      "scorePct": 33,
      "tovPct": 7.5,
      "fgMiss": 63,
      "fgMade": 33,
      "sfPct": 4.7,
      "totalPts": -1,
      "totalScorePct": -1,
      "totalPlays": -1,
      "uncatPts": -1,
      "uncatPlays": -1,
      "uncatScorePct": -1,
      "uncatPtsPerScPlay": -1,
      "totalSfPlays": -1,
      "totalTos": -1,
      "totalFgMade": -1,
      "totalFgMiss": -1,
      "uncatSfPlays": -1,
      "uncatTos": -1,
      "uncatFgMade": -1,
      "uncatFgMiss": -1
   },
   {
      "code": "PlayerTwo",
      "title": "#1 Player Two",
      "pts": 129,
      "plays": 169,
      "scorePct": 30.8,
      "tovPct": 13.6,
      "fgMiss": 92,
      "fgMade": 46,
      "sfPct": 3,
      "totalPts": -1,
      "totalScorePct": -1,
      "totalPlays": -1,
      "uncatPts": -1,
      "uncatPlays": -1,
      "uncatScorePct": -1,
      "uncatPtsPerScPlay": -1,
      "totalSfPlays": -1,
      "totalTos": -1,
      "totalFgMade": -1,
      "totalFgMiss": -1,
      "uncatSfPlays": -1,
      "uncatTos": -1,
      "uncatFgMade": -1,
      "uncatFgMiss": -1
   },
   {
      "code": "PlayerThree",
      "title": "#3 Player Three",
      "pts": 186,
      "plays": 179,
      "scorePct": 43.6,
      "tovPct": 7.3,
      "fgMiss": 88,
      "fgMade": 70,
      "sfPct": 3.4,
      "totalPts": -1,
      "totalScorePct": -1,
      "totalPlays": -1,
      "uncatPts": -1,
      "uncatPlays": -1,
      "uncatScorePct": -1,
      "uncatPtsPerScPlay": -1,
      "totalSfPlays": -1,
      "totalTos": -1,
      "totalFgMade": -1,
      "totalFgMiss": -1,
      "uncatSfPlays": -1,
      "uncatTos": -1,
      "uncatFgMade": -1,
      "uncatFgMiss": -1
   },
   {
      "code": "PlayerFour",
      "title": "#4 Player Four",
      "pts": 88,
      "plays": 130,
      "scorePct": 29.2,
      "tovPct": 9.2,
      "fgMiss": 80,
      "fgMade": 35,
      "sfPct": 3.1,
      "totalPts": -1,
      "totalScorePct": -1,
      "totalPlays": -1,
      "uncatPts": -1,
      "uncatPlays": -1,
      "uncatScorePct": -1,
      "uncatPtsPerScPlay": -1,
      "totalSfPlays": -1,
      "totalTos": -1,
      "totalFgMade": -1,
      "totalFgMiss": -1,
      "uncatSfPlays": -1,
      "uncatTos": -1,
      "uncatFgMade": -1,
      "uncatFgMiss": -1
   },
   {
      "code": "PlayerFive",
      "title": "#5 Player Five",
      "pts": 55,
      "plays": 81,
      "scorePct": 29.6,
      "tovPct": 11.1,
      "fgMiss": 47,
      "fgMade": 17,
      "sfPct": 6.2,
      "totalPts": -1,
      "totalScorePct": -1,
      "totalPlays": -1,
      "uncatPts": -1,
      "uncatPlays": -1,
      "uncatScorePct": -1,
      "uncatPtsPerScPlay": -1,
      "totalSfPlays": -1,
      "totalTos": -1,
      "totalFgMade": -1,
      "totalFgMiss": -1,
      "uncatSfPlays": -1,
      "uncatTos": -1,
      "uncatFgMade": -1,
      "uncatFgMiss": -1
   },
   {
      "code": "PlayerSix",
      "title": "#6 Player Six",
      "pts": 53,
      "plays": 66,
      "scorePct": 39.4,
      "tovPct": 13.6,
      "fgMiss": 30,
      "fgMade": 21,
      "sfPct": 4.5,
      "totalPts": -1,
      "totalScorePct": -1,
      "totalPlays": -1,
      "uncatPts": -1,
      "uncatPlays": -1,
      "uncatScorePct": -1,
      "uncatPtsPerScPlay": -1,
      "totalSfPlays": -1,
      "totalTos": -1,
      "totalFgMade": -1,
      "totalFgMiss": -1,
      "uncatSfPlays": -1,
      "uncatTos": -1,
      "uncatFgMade": -1,
      "uncatFgMiss": -1
   },
   {
      "code": "PlayerSeven",
      "title": "#7 Player Seven",
      "pts": 55,
      "plays": 57,
      "scorePct": 40.4,
      "tovPct": 14,
      "fgMiss": 25,
      "fgMade": 19,
      "sfPct": 8.8,
      "totalPts": -1,
      "totalScorePct": -1,
      "totalPlays": -1,
      "uncatPts": -1,
      "uncatPlays": -1,
      "uncatScorePct": -1,
      "uncatPtsPerScPlay": -1,
      "totalSfPlays": -1,
      "totalTos": -1,
      "totalFgMade": -1,
      "totalFgMiss": -1,
      "uncatSfPlays": -1,
      "uncatTos": -1,
      "uncatFgMade": -1,
      "uncatFgMiss": -1
   },
   {
      "code": "PlayerEight",
      "title": "#8 Player Eight",
      "pts": 69,
      "plays": 89,
      "scorePct": 33.7,
      "tovPct": 13.5,
      "fgMiss": 46,
      "fgMade": 29,
      "sfPct": 3.4,
      "totalPts": -1,
      "totalScorePct": -1,
      "totalPlays": -1,
      "uncatPts": -1,
      "uncatPlays": -1,
      "uncatScorePct": -1,
      "uncatPtsPerScPlay": -1,
      "totalSfPlays": -1,
      "totalTos": -1,
      "totalFgMade": -1,
      "totalFgMiss": -1,
      "uncatSfPlays": -1,
      "uncatTos": -1,
      "uncatFgMade": -1,
      "uncatFgMiss": -1
   }
] ];