export const freshmenMen2024_25: Record<string, any> = {
  "New Mexico": {
    "Milicevic, Jovan": {
      pos: "PF/C",
      pr: "3*",
      c: "JoMilicevic",
      h: "6-10",
      r: -29,
    },
  },
  "Texas A&M": {
    "Turkson, George": {
      pos: "S-PF",
      pr: "3.5*/T150ish",
      c: "GeTurkson",
      h: "6-7",
      r: 46,
    },
    "Mills, Andre": {
      pos: "WG",
      pr: "3.5*/T150ish",
      c: "AnMills",
      h: "6-4",
      r: 42,
    },
  },
  Clemson: {
    "Thomas, Dallas": {
      pos: "S-PF",
      pr: "4*",
      c: "DaThomas",
      h: "6-7",
      r: -10,
    },
  },
  BYU: {
    "Catchings, Kanon": {
      pos: "S-PF",
      pr: "4*/T40ish",
      c: "KaCatchings",
      h: "6-8",
      r: -2,
    },
    "Kozlowski, Brody": {
      pos: "S-PF",
      pr: "3.5*/T150ish",
      c: "BrKozlowski",
      h: "6-7",
      r: 97,
    },
    "Crawford, Elijah": {
      pos: "PG",
      pr: "3.5*/T150ish",
      c: "ElCrawford",
      h: "6-1",
      r: 43,
    },
  },
  Providence: {
    "Erhunmwunse, Oswin": {
      pos: "C",
      pr: "4*",
      c: "OsErhunmwuns",
      h: "6-10",
      r: -86,
    },
  },
  "San Diego St.": {
    "Compton, Pharaoh": {
      pos: "WF",
      pr: "3.5*/T150ish",
      c: "PhCompton",
      h: "6-6",
      r: 59,
    },
  },
  Auburn: {
    "Pettiford, Tahaad": {
      pos: "PG",
      pr: "5*",
      c: "TaPettiford",
      h: "6-1",
      r: -94,
    },
    "Howard, Jahki": {
      pos: "WG",
      pr: "4*",
      c: "JaHoward",
      h: "6-6",
      r: 48,
    },
  },
  Washington: {
    "Diallo, Zoom": {
      pos: "PG",
      pr: "4*/T40ish",
      c: "ZoDiallo",
      h: "6-4",
      r: -8,
    },
    "Butler, Jase": {
      pos: "CG",
      pr: "3.5*/T150ish",
      c: "JaButler",
      h: "6-4",
      r: 58,
    },
  },
  "Ole Miss": {
    "Bol, John": {
      pos: "C",
      pr: "4*",
      c: "JoBol",
      h: "7-1",
      r: 98,
    },
  },
  Florida: {
    "Brown, Isaiah": {
      pos: "WG",
      pr: "3.5*/T150ish",
      c: "IsBrown",
      h: "6-5",
      r: 48,
    },
  },
  "Georgia Tech": {
    "Mustaf, Jaeden": {
      pos: "CG",
      pr: "4*",
      c: "JaMustaf",
      h: "6-4",
      r: 94,
    },
    "Sutton, Darrion": {
      pos: "WF",
      pr: "3.5*/T150ish",
      c: "DaSutton",
      h: "6-8",
      r: 77,
    },
    "Onwuchekwa, Doryan": {
      pos: "C",
      pr: "3.5*/T150ish",
      c: "DoOnwuchekwa",
      h: "6-10",
      r: 41,
    },
  },
  "Florida St.": {
    "Davis, Daquan": {
      pos: "PG",
      pr: "3.5*/T150ish",
      c: "DaDavis",
      h: "6-1",
      r: 66,
    },
  },
  "South Carolina": {
    "Scott, Cam": {
      pos: "WG",
      pr: "4*/T40ish",
      c: "CaScott",
      h: "6-5",
      r: 42,
    },
  },
  "Arizona St.": {
    "Quaintance, Jayden": {
      pos: "C",
      pr: "5*/Lotto",
      c: "JaQuaintance",
      h: "6-9",
      r: -62,
    },
    "Sanon, Joson": {
      pos: "WG",
      pr: "5*",
      c: "JoSanon",
      h: "6-5",
      r: -68,
    },
    "Ali, Amier": {
      pos: "WF",
      pr: "4*",
      c: "AmAli",
      h: "6-8",
      r: 9,
    },
  },
  Villanova: {
    "Hodge, Matthew": {
      pos: "S-PF",
      pr: "4*",
      c: "MaHodge",
      h: "6-8",
      r: 28,
    },
    "Moseley, Josiah": {
      pos: "WF",
      pr: "4*",
      c: "JoMoseley",
      h: "6-6",
      r: -27,
    },
  },
  "Iowa St.": {
    "Indrusaitis, Nojus": {
      pos: "WG",
      pr: "4*",
      c: "NoIndrusaiti",
      h: "6-5",
      r: 13,
    },
  },
  Arkansas: {
    "Fland, Boogie": {
      pos: "CG",
      pr: "5*",
      c: "BoFland",
      h: "6-2",
      r: -14,
    },
    "Knox, Karter": {
      pos: "WG",
      pr: "5*",
      c: "KaKnox",
      h: "6-5",
      r: -52,
    },
    "Richmond, Billy": {
      pos: "WG",
      pr: "5*",
      c: "BiRichmond",
      h: "6-5",
      r: -86,
    },
  },
  UCLA: {
    "Perry, Trent": {
      pos: "PG",
      pr: "4*/T40ish",
      c: "TrPerry",
      h: "6-4",
      r: 80,
    },
  },
  "Ohio St.": {
    "Mobley Jr., John": {
      pos: "CG",
      pr: "4*/T40ish",
      c: "JoMobley",
      h: "6-2",
      r: -76,
    },
  },
  Marquette: {
    "Owens, Damarius": {
      pos: "WF",
      pr: "4*",
      c: "DaOwens",
      h: "6-8",
      r: 59,
    },
    "Parham, Royce": {
      pos: "S-PF",
      pr: "3.5*/T150ish",
      c: "RoParham",
      h: "6-8",
      r: 78,
    },
  },
  "Southern California": {
    "Elohim, Isaiah": {
      pos: "WG",
      pr: "4*/T40ish",
      c: "IsElohim",
      h: "6-5",
      r: -74,
    },
    "Shelley, Jalen": {
      pos: "WF",
      pr: "4*",
      c: "JaShelley",
      h: "6-8",
      r: 62,
    },
  },
  Texas: {
    "Johnson, Tre": {
      pos: "WG",
      pr: "5*/Lotto",
      c: "TrJohnson",
      h: "6-6",
      r: -34,
    },
    "Codie, Nicolas": {
      pos: "PF/C",
      pr: "4*",
      c: "NiCodie",
      h: "6-9",
      r: 66,
    },
  },
  Tennessee: {
    "Boswell, Bishop": {
      pos: "CG",
      pr: "4*",
      c: "BiBoswell",
      h: "6-4",
      r: 21,
    },
  },
  Utah: {
    "Johnson, Jaxon": {
      pos: "S-PF",
      pr: "4*",
      c: "JaJohnson",
      h: "6-8",
      r: -29,
    },
  },
  Houston: {
    "McCarty, Chase": {
      pos: "WG",
      pr: "4*",
      c: "ChMccarty",
      h: "6-5",
      r: -4,
    },
    "Miller, Mercy": {
      pos: "WG",
      pr: "4*",
      c: "MeMiller",
      h: "6-4",
      r: -31,
    },
  },
  Georgia: {
    "Newell, Asa": {
      pos: "PF/C",
      pr: "5*/Lotto",
      c: "AsNewell",
      h: "6-9",
      r: -96,
    },
    "Cyril, Somto": {
      pos: "C",
      pr: "4*/T40ish",
      c: "SoCyril",
      h: "6-10",
      r: -30,
    },
  },
  Missouri: {
    "Boateng, Annor": {
      pos: "WG",
      pr: "4*/T40ish",
      c: "AnBoateng",
      h: "6-6",
      r: 68,
    },
    "Allen, Marcus": {
      pos: "WF",
      pr: "4*",
      c: "MaAllen",
      h: "6-6",
      r: 41,
    },
    "Marshall, Peyton": {
      pos: "C",
      pr: "3.5*/T150ish",
      c: "PeMarshall",
      h: "7-0",
      r: 83,
    },
    "Burns, Trent": {
      pos: "C",
      pr: "3.5*/T150ish",
      c: "TrBurns",
      h: "7-3",
      r: 81,
    },
  },
  TCU: {
    "Robinson, Micah": {
      pos: "WG",
      pr: "4*",
      c: "MiRobinson",
      h: "6-6",
      r: -22,
    },
    "Punch, David": {
      pos: "S-PF",
      pr: "4*",
      c: "DaPunch",
      h: "6-7",
      r: -95,
    },
  },
  "Wake Forest": {
    "Harris, Juke": {
      pos: "WG",
      pr: "4*",
      c: "JuHarris",
      h: "6-6",
      r: -34,
    },
  },
  Oklahoma: {
    "Atak, Kuol": {
      pos: "PF/C",
      pr: "3.5*/T150ish",
      c: "KuAtak",
      h: "6-9",
      r: 54,
    },
  },
  UCF: {
    "Thiam, Moustapha": {
      pos: "C",
      pr: "4*",
      c: "MoThiam",
      h: "7-1",
      r: 92,
    },
  },
  Cincinnati: {
    "Betsey, Tyler": {
      pos: "S-PF",
      pr: "4*/T40ish",
      c: "TyBetsey",
      h: "6-8",
      r: -54,
    },
    "McKinley, Tyler": {
      pos: "C",
      pr: "4*",
      c: "TyMckinley",
      h: "6-8",
      r: 27,
    },
  },
  "North Carolina": {
    "Jackson, Ian": {
      pos: "WG",
      pr: "5*/Lotto",
      c: "IaJackson",
      h: "6-5",
      r: -60,
    },
    "Powell, Drake": {
      pos: "WG",
      pr: "5*/Lotto",
      c: "DrPowell",
      h: "6-6",
      r: -92,
    },
    "Brown, James": {
      pos: "C",
      pr: "4*",
      c: "JaBrown",
      h: "6-9",
      r: -36,
    },
  },
  Virginia: {
    "Cofie, Jacob": {
      pos: "PF/C",
      pr: "4*",
      c: "JaCofie",
      h: "6-9",
      r: -30,
    },
  },
  LSU: {
    "Miller, Vyctorius": {
      pos: "WG",
      pr: "4*",
      c: "VyMiller",
      h: "6-5",
      r: 86,
    },
    "Givens III, Curtis": {
      pos: "PG",
      pr: "4*",
      c: "CuGivens",
      h: "6-2",
      r: 47,
    },
    "Miller, Robert": {
      pos: "PF/C",
      pr: "4*",
      c: "RoMiller",
      h: "6-10",
      r: 45,
    },
  },
  Alabama: {
    "Reid, Derrion": {
      pos: "S-PF",
      pr: "5*/Lotto",
      c: "DeReid",
      h: "6-7",
      r: -86,
    },
    "Sherrell, Aiden": {
      pos: "C",
      pr: "5*",
      c: "AiSherrell",
      h: "6-10",
      r: -54,
    },
    "Philon, Labaron": {
      pos: "PG",
      pr: "4*/T40ish",
      c: "LaPhilon",
      h: "6-4",
      r: 60,
    },
    "Cunningham, Naas": {
      pos: "WF",
      pr: "4*/T40ish",
      c: "NaCunningham",
      h: "6-7",
      r: -42,
    },
  },
  Syracuse: {
    "Freeman, Donnie": {
      pos: "PF/C",
      pr: "5*/Lotto",
      c: "DoFreeman",
      h: "6-9",
      r: -94,
    },
    "Moore, Elijah": {
      pos: "WG",
      pr: "3.5*/T150ish",
      c: "ElMoore",
      h: "6-4",
      r: 90,
    },
  },
  "Virginia Tech": {
    "Jones, Ryan": {
      pos: "C",
      pr: "4*",
      c: "RyJones",
      h: "6-8",
      r: -22,
    },
  },
  Duke: {
    "Maluach, Khaman": {
      pos: "C",
      pr: "5*/Lotto",
      c: "KhMaluach",
      h: "7-1",
      r: -38,
    },
    "Flagg, Cooper": {
      pos: "PF/C",
      pr: "5*/Lotto",
      c: "CoFlagg",
      h: "6-9",
      r: 0,
    },
    "Knueppel, Kon": {
      pos: "WG",
      pr: "5*",
      c: "KoKnueppel",
      h: "6-5",
      r: -6,
    },
    "Harris, Darren": {
      pos: "WG",
      pr: "4*/T40ish",
      c: "DaHarris",
      h: "6-6",
      r: 18,
    },
    "Evans, Isaiah": {
      pos: "WG",
      pr: "5*/Lotto",
      c: "IsEvans",
      h: "6-6",
      r: -98,
    },
    "Ngongba II, Patrick": {
      pos: "C",
      pr: "5*",
      c: "PaNgongba",
      h: "6-11",
      r: -82,
    },
  },
  Indiana: {
    "Tucker, Bryson": {
      pos: "WG",
      pr: "5*",
      c: "BrTucker",
      h: "6-6",
      r: -40,
    },
  },
  "Saint Mary's (CA)": {
    "Lewis, Mikey": {
      pos: "CG",
      pr: "4*",
      c: "MiLewis",
      h: "6-3",
      r: -43,
    },
    "Campbell, Liam": {
      pos: "WG",
      pr: "3.5*/T150ish",
      c: "LiCampbell",
      h: "6-4",
      r: 78,
    },
  },
  Purdue: {
    "Harris, Gicarri": {
      pos: "CG",
      pr: "4*",
      c: "GiHarris",
      h: "6-4",
      r: 30,
    },
  },
  Baylor: {
    "Edgecombe, VJ": {
      pos: "WG",
      pr: "5*/Lotto",
      c: "VjEdgecombe",
      h: "6-5",
      r: -22,
    },
    "Wright, Rob": {
      pos: "PG",
      pr: "5*",
      c: "RoWright",
      h: "6-0",
      r: -86,
    },
    "Asemota, Jason": {
      pos: "WF",
      pr: "4*/T40ish",
      c: "JaAsemota",
      h: "6-8",
      r: -76,
    },
  },
  Kentucky: {
    "Perry, Travis": {
      pos: "PG",
      pr: "4*",
      c: "TrPerry",
      h: "6-2",
      r: -10,
    },
    "Noah, Trent": {
      pos: "WG",
      pr: "3.5*/T150ish",
      c: "TrNoah",
      h: "6-6",
      r: 71,
    },
  },
  "St. John's (NY)": {
    "Glover, Jaiden": {
      pos: "WG",
      pr: "4*/T40ish",
      c: "JaGlover",
      h: "6-5",
      r: -96,
    },
  },
  Memphis: {
    "Harris, Jared": {
      pos: "WG",
      pr: "4*",
      c: "JaHarris",
      h: "6-2",
      r: -52,
    },
  },
  Ohio: {
    "Evans, Ayden": {
      pos: "C",
      pr: "3*",
      c: "AyEvans",
      h: "6-8",
      r: 0,
    },
  },
  "Kansas St.": {
    "Castillo, David": {
      pos: "CG",
      pr: "4*/T40ish",
      c: "DaCastillo",
      h: "6-1",
      r: -98,
    },
  },
  "Notre Dame": {
    "Mohammed, Sir": {
      pos: "CG",
      pr: "4*",
      c: "SiMohammed",
      h: "6-7",
      r: 32,
    },
  },
  Illinois: {
    "Johnson, Morez": {
      pos: "C",
      pr: "4*/T40ish",
      c: "MoJohnson",
      h: "6-9",
      r: 96,
    },
  },
  Georgetown: {
    "Sorber, Thomas": {
      pos: "C",
      pr: "4*/T40ish",
      c: "ThSorber",
      h: "6-9",
      r: -28,
    },
    "Mulready, Kayvaun": {
      pos: "WG",
      pr: "4*",
      c: "KaMulready",
      h: "6-4",
      r: 27,
    },
  },
  Louisville: {
    "Rooths, Khani": {
      pos: "S-PF",
      pr: "4*/T40ish",
      c: "KhRooths",
      h: "6-8",
      r: 64,
    },
  },
  Harvard: {
    "Hinton, Robert": {
      pos: "WG",
      pr: "3.5*/T150ish",
      c: "RoHinton",
      h: "6-4",
      r: 100,
    },
  },
  Kansas: {
    "Bidunga, Flory": {
      pos: "C",
      pr: "5*",
      c: "FlBidunga",
      h: "6-8",
      r: -2,
    },
    "Passmore, Rakease": {
      pos: "WG",
      pr: "4*/T40ish",
      c: "RaPassmore",
      h: "6-5",
      r: 4,
    },
  },
  Tulane: {
    "Greene, Kyle": {
      pos: "CG",
      pr: "3.5*/T150ish",
      c: "KyGreene",
      h: "6-2",
      r: 75,
    },
  },
  "NC State": {
    "McNeil, Paul": {
      pos: "WG",
      pr: "4*/T40ish",
      c: "PaMcneil",
      h: "6-6",
      r: -98,
    },
  },
  Maryland: {
    "Queen, Derik": {
      pos: "C",
      pr: "5*/Lotto",
      c: "DeQueen",
      h: "6-10",
      r: -92,
    },
  },
  "Miami (FL)": {
    "Bethea, Jalil": {
      pos: "WG",
      pr: "5*/Lotto",
      c: "JaBethea",
      h: "6-4",
      r: -40,
    },
    "Swartz, Austin": {
      pos: "WG",
      pr: "4*/T40ish",
      c: "AuSwartz",
      h: "6-4",
      r: -70,
    },
  },
  Creighton: {
    "McAndrew, Jackson": {
      pos: "PF/C",
      pr: "4*/T40ish",
      c: "JaMcandrew",
      h: "6-9",
      r: 18,
    },
    "Johnson, Larry": {
      pos: "WG",
      pr: "3.5*/T150ish",
      c: "LaJohnson",
      h: "6-4",
      r: 55,
    },
  },
  Iowa: {
    "Koch, Cooper": {
      pos: "S-PF",
      pr: "4*",
      c: "CoKoch",
      h: "6-8",
      r: -30,
    },
  },
  UConn: {
    "McNeeley, Liam": {
      pos: "WF",
      pr: "5*",
      c: "LiMcneeley",
      h: "6-7",
      r: -4,
    },
    "Nowell, Ahmad": {
      pos: "CG",
      pr: "4*/T40ish",
      c: "AhNowell",
      h: "6-0",
      r: 34,
    },
    "Abraham, Isaiah": {
      pos: "S-PF",
      pr: "4*",
      c: "IsAbraham",
      h: "6-7",
      r: 5,
    },
  },
  "Penn St.": {
    "Goodman, Miles": {
      pos: "C",
      pr: "3.5*/T150ish",
      c: "MiGoodman",
      h: "6-10",
      r: 73,
    },
  },
  Rutgers: {
    "Bailey, Ace": {
      pos: "WF",
      pr: "5*/Lotto",
      c: "AcBailey",
      h: "6-8",
      r: -8,
    },
    "Harper, Dylan": {
      pos: "CG",
      pr: "5*/Lotto",
      c: "DyHarper",
      h: "6-6",
      r: -16,
    },
  },
  Arizona: {
    "Bryant, Carter": {
      pos: "S-PF",
      pr: "5*",
      c: "CaBryant",
      h: "6-8",
      r: -56,
    },
    "Stephen, Emmanuel": {
      pos: "C",
      pr: "4*",
      c: "EmStephen",
      h: "7-0",
      r: -49,
    },
  },
  Colorado: {
    "Crawford, Andrew": {
      pos: "CG",
      pr: "3.5*/T150ish",
      c: "AnCrawford",
      h: "6-6",
      r: 58,
    },
  },
  Michigan: {
    "Pippen, Justin": {
      pos: "CG",
      pr: "3.5*/T150ish",
      c: "JuPippen",
      h: "6-3",
      r: 75,
    },
  },
  Oregon: {
    "Phillips, Jamari": {
      pos: "WG",
      pr: "4*/T40ish",
      c: "JaPhillips",
      h: "6-3",
      r: -70,
    },
  },
  "Michigan St.": {
    "Richardson, Jase": {
      pos: "CG",
      pr: "4*/T40ish",
      c: "JaRichardson",
      h: "6-3",
      r: 72,
    },
    "Teng, Kur": {
      pos: "WG",
      pr: "4*/T40ish",
      c: "KuTeng",
      h: "6-4",
      r: -88,
    },
  },
};
